// Demonstration listings have no real contacts, private addresses or invented map coordinates.
export function directorySeed(){
  const common={data_status:'demo',is_active:1,availability:'inquiry',price:null,contact_consent:0,location_consent:0,terms:'Data contoh untuk demonstrasi EcoQuest. Harga dan layanan ini bukan penawaran nyata.'};
  return [
    {table:'tourism_stays',row:{...common,id:'contoh-rumah-pesisir',slug:'contoh-rumah-pesisir',name:'Rumah Singgah Pesisir (contoh)',short_description:'Contoh rumah sewa untuk keluarga yang ingin menikmati suasana pesisir bersama warga.',description:'Contoh format informasi rumah sewa milik warga: kapasitas, fasilitas, tarif, dan cara menghubungi pemilik. Belum mewakili penginapan yang beroperasi.',area:'Kawasan pesisir Marga Mulya — lokasi contoh',stay_type:'Rumah sewa',capacity:6,bedrooms:2,price:350000,amenities:'Dapur bersama\nRuang keluarga\nArea parkir',check_in:'14.00',check_out:'11.00',accessibility:'Kondisi akses belum diperiksa.',sort_order:10}},
    {table:'tourism_stays',row:{...common,id:'contoh-kamar-warga',slug:'contoh-kamar-warga',name:'Kamar Tamu Warga (contoh)',short_description:'Contoh kamar sederhana untuk wisatawan yang ingin mengenal kehidupan desa.',description:'Data contoh kamar tamu; fasilitas dan tarif hanya untuk memperagakan direktori layanan warga.',area:'Lingkungan permukiman Marga Mulya — lokasi contoh',stay_type:'Kamar tamu',capacity:2,bedrooms:1,price:150000,amenities:'Kamar tamu\nKipas angin\nKamar mandi bersama',sort_order:20}},
    {table:'tourism_guides',row:{...common,id:'contoh-pemandu-pesisir',slug:'contoh-pemandu-pesisir',name:'Jelajah Pesisir Bersama Warga (contoh)',short_description:'Contoh pendampingan mengenal pesisir, kehidupan nelayan, dan usaha lokal.',description:'Contoh layanan pemandu lokal untuk kelompok kecil. Rute, cuaca, titik temu, dan keselamatan perlu dikonfirmasi sebelum kegiatan.',area:'Pesisir Marga Mulya — wilayah layanan contoh',languages:'Bahasa Indonesia',specialties:'Jelajah pesisir\nCerita kehidupan nelayan\nKunjungan UMKM',capacity:6,duration_hours:3,price:200000,rate_unit:'per kelompok',inclusions:'Pendampingan pemandu\nPenjelasan budaya setempat',exclusions:'Transportasi\nMakan dan minum\nTiket destinasi',sort_order:10}},
    {table:'tourism_guides',row:{...common,id:'contoh-pemandu-umkm',slug:'contoh-pemandu-umkm',name:'Cerita Usaha Desa (contoh)',short_description:'Contoh perjalanan singkat mengenal produk dan keterampilan warga.',description:'Contoh pendampingan wisata edukasi usaha warga. Jadwal kunjungan mengikuti kesediaan pelaku usaha.',area:'Marga Mulya — wilayah layanan contoh',languages:'Bahasa Indonesia',specialties:'Wisata edukasi\nKunjungan usaha warga',capacity:4,duration_hours:2,price:120000,rate_unit:'per kelompok',inclusions:'Pendampingan selama kunjungan',exclusions:'Belanja produk\nTransportasi',sort_order:20}}
  ];
}
