import RegistrationAdmin from './registration-admin.jsx';
import {EnrollmentSettings} from './event-registration.jsx';
import {TableManager,ComplaintsAdmin,Inbox,PortalDashboard} from './portal-admin.jsx';
import React,{useEffect,useState}from'react';
import{LayoutDashboard,Newspaper,CalendarDays,Store,Images,Settings,LogOut,ExternalLink,Plus,Search,Pencil,Trash2,ShieldCheck,KeyRound,Save,FileText,Menu,X,Landmark,MapPinned,BarChart3,Megaphone,CircleHelp,Bot,MessageSquare,TreePalm,Building2,HardHat,HeartHandshake,PhoneCall,Eye,EyeOff,LayoutTemplate,ArrowUp,ArrowDown}from'lucide-react';
import{api,Link,Busy,Notice,Field,ImageField,MultiImageField,BrandMark,imagesOf,Modal,Picture,Empty,dateLabel,today,statusLabel}from'./lib.jsx';
import{homeSectionKeys,homeSectionLabels}from'../server/portal-schema.mjs';
// Grouped admin menu. Keys map to record kinds (article/event/…), portal tables, or special screens.
const menu=[
 [null,[['dashboard','Dashboard',LayoutDashboard]]],
 ['KONTEN',[['site:beranda','Tampilan Beranda',LayoutTemplate],['article','Berita & pengumuman',Newspaper],['gallery','Galeri',Images],['event','Agenda desa',CalendarDays],['registration','Pendaftaran kegiatan',FileText],['product','Lapak & pengajuan',Store]]],
 ['DESA',[['site:profil','Profil desa',Landmark],['village_areas','Wilayah / Dusun',MapPinned],['site:data','Statistik',BarChart3]]],
 ['LAYANAN',[['complaints','Pengaduan',Megaphone],['faqs','FAQ',CircleHelp],['chatbot_nodes','Chatbot',Bot],['inbox','Pesan Warga',MessageSquare]]],
 ['POTENSI',[['tourism_places','Wisata',TreePalm],['public_facilities','Fasilitas Umum',Building2]]],
 ['PEMERINTAHAN',[['development_projects','Pembangunan',HardHat],['aid_programs','Bantuan Sosial',HeartHandshake]]],
 ['LAINNYA',[['emergency_contacts','Nomor Darurat',PhoneCall],['site','Pengaturan Website',Settings],['account','Akun admin',KeyRound]]]
];
const modules=menu.flatMap(([,items])=>items);
const menu_groups=menu;
const portalTables=['village_areas','faqs','chatbot_nodes','tourism_places','public_facilities','development_projects','aid_programs','emergency_contacts'];
const moduleHelp={
 village_areas:'Atur daftar dusun dan RT/RW yang dipakai pada formulir warga. Pilih “RT / RW di wilayah ini” pada setiap dusun untuk menambah RT/RW.',
 faqs:'Pertanyaan umum tampil di halaman Layanan warga dan menu FAQ Asisten Desa. Gunakan panah untuk mengubah urutan.',
 chatbot_nodes:'Setiap menu berisi pesan bot dan pilihan bernomor. Buka “Pilihan balasan” untuk menambah, mengubah nomor, atau mengatur tujuan pilihan. Menu utama adalah menu pertama yang dilihat warga.',
 tourism_places:'Destinasi aktif tampil di halaman Wisata, beranda, dan sebagai penanda di Peta Desa. Isi harga tiket dan jam buka hanya jika sudah dikonfirmasi.',
 public_facilities:'Fasilitas aktif tampil sebagai penanda di Peta Desa sesuai kategorinya.',
 development_projects:'Proyek terbit tampil di halaman Pembangunan dan beranda. Tambahkan foto sebelum/proses/selesai melalui “Dokumentasi & timeline progres”.',
 aid_programs:'Setiap program memiliki Penerima dan Dokumentasi penyaluran. Daftar penerima hanya tampil (tersamar) jika opsi tampilkan daftar penerima diaktifkan.',
 emergency_contacts:'Nomor aktif tampil di tombol Darurat pada semua halaman. Nomor nasional: 112, 110, 119, 113. Perbarui kontak lokal bila berubah.'
};
const kindNames={article:'informasi',event:'agenda',product:'produk',gallery:'foto'};
const galleryCategories=['Kegiatan Desa','Pembangunan','Budaya','Wisata','UMKM','Masyarakat'];
function Login({onLogin}){
 const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="login-page"><div className="login-art"><span className="eyebrow light">PENGELOLAAN WEBSITE DESA</span><h1>Informasi yang terawat,<br/>warga yang terhubung.</h1><p>Kelola profil, kabar masyarakat, agenda, dan usaha warga dari satu ruang kerja.</p><Link href="/">Kembali ke website desa</Link></div><main className="login-form"><span className="login-icon"><ShieldCheck/></span><h2>Masuk sebagai admin</h2><p>Gunakan akun pengelola website desa.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/login',{method:'POST',body:{email,password}});onLogin();}catch(x){setError(x.message);}finally{setBusy(false);}}}><Field label="Email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/><Field label="Kata sandi" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/><Notice error>{error}</Notice><button className="button full" disabled={busy}>{busy?'Memeriksa akun…':'Masuk'}</button></form><p className="small muted">Akses ini hanya untuk pengelola. Pengunjung dapat membaca informasi tanpa masuk.</p><Link href="/" className="plain-link">Lihat halaman pengunjung</Link></main></div>;
}
function RecordEditor({kind,record,site,products,onClose,onSaved}){
 const defaults={title:'',category:kind==='product'?site.productCategories[0]:kind==='event'?site.eventCategories[0]:kind==='gallery'?'Kegiatan Desa':'Pengumuman',description:'',excerpt:'',body:'',image:'',imageCredit:'',date:today(),endDate:today(),time:'08:00',endTime:'12:00',location:'',organizer:'',contact:'',eventStatus:'Terjadwal',productIds:[],price:0,unit:'buah',seller:'',area:'',phone:'',availability:'Tersedia',consent:false,featured:false,status:'draft',moderationNote:'',sortOrder:100};
 const[f,setF]=useState({...defaults,...record}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const ch=(k,v)=>{setF(o=>({...o,[k]:v}));setDirty(true);};
 const close=()=>{if(!dirty||confirm('Perubahan belum disimpan. Tutup editor?'))onClose();};
 const input=(k,label,type='text',required=true)=><Field label={label} type={type} required={required} value={f[k]??''} onChange={e=>ch(k,e.target.value)}/>;
 const text=(k,label,required=true)=><Field label={label}><textarea required={required} value={f[k]||''} onChange={e=>ch(k,e.target.value)}/></Field>;
 return <Modal title={(record?'Edit ':'Tambah ')+kindNames[kind]} onClose={close} wide><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api(record?'/admin/records/'+record.id:'/admin/records',{method:record?'PUT':'POST',body:{...f,images:imagesOf(f),kind}});setDirty(false);await onSaved();}catch(x){setError(x.message);}finally{setBusy(false);}}}><div className="form-grid">{input('title',kind==='product'?'Nama produk':'Judul')}{(kind==='event'||kind==='product')?<Field label="Kategori"><select value={f.category} onChange={e=>ch('category',e.target.value)}>{[...new Set([...(kind==='event'?site.eventCategories:site.productCategories),f.category])].filter(Boolean).map(c=><option key={c}>{c}</option>)}</select></Field>:kind==='gallery'?<Field label="Kategori" required list="gallery-categories" help="Contoh: Kegiatan Desa, Pembangunan, Budaya, Wisata, UMKM, Masyarakat" value={f.category} onChange={e=>ch('category',e.target.value)}/>:input('category','Kategori')}</div>
 {kind==='article'&&<>{input('date','Tanggal','date')}{text('excerpt','Ringkasan')}{text('body','Isi informasi')}</>}
 {kind==='event'&&<><div className="form-grid">{input('date','Tanggal mulai','date')}{input('endDate','Tanggal selesai','date')}{input('time','Waktu mulai','time')}{input('endTime','Waktu selesai','time')}{input('location','Lokasi')}{input('organizer','Penyelenggara')}</div>{text('description','Keterangan kegiatan')}{input('contact','Kontak penyelenggara','text',false)}<Field label="Status kegiatan"><select value={f.eventStatus} onChange={e=>ch('eventStatus',e.target.value)}>{['Terjadwal','Ditunda','Dibatalkan','Selesai'].map(v=><option key={v}>{v}</option>)}</select></Field><EnrollmentSettings form={f} change={ch}/><fieldset className="checkbox-group"><legend>Produk terkait (opsional)</legend>{products.filter(p=>p.status==='published').map(p=><label className="check-field" key={p.id}><input type="checkbox" checked={f.productIds.includes(p.id)} onChange={e=>ch('productIds',e.target.checked?[...f.productIds,p.id]:f.productIds.filter(id=>id!==p.id))}/><span>{p.title}</span></label>)}<small>Hubungkan hanya produk yang memang terkait dengan kegiatan.</small></fieldset></>}
 {kind==='product'&&<><div className="form-grid">{input('price','Harga (Rp)','number')}{input('unit','Satuan')}{input('seller','Nama usaha / penjual')}{input('area','Dusun / wilayah usaha')}{input('phone','WhatsApp penjual','tel',false)}<Field label="Ketersediaan"><select value={f.availability} onChange={e=>ch('availability',e.target.value)}>{['Tersedia','Pesan dahulu','Habis'].map(v=><option key={v}>{v}</option>)}</select></Field></div>{text('description','Deskripsi produk')}<label className="check-field"><input type="checkbox" checked={f.consent} onChange={e=>ch('consent',e.target.checked)}/><span>Penjual mengizinkan kontak ditampilkan pada halaman produk.</span></label></>}
 {kind==='gallery'&&<>{text('description','Keterangan / teks alternatif')}<div className="form-grid">{input('date','Tanggal dokumentasi','date')}{input('sortOrder','Urutan tampil (angka kecil tampil lebih dulu)','number',false)}</div><datalist id="gallery-categories">{galleryCategories.map(c=><option key={c} value={c}/>)}</datalist></>}
 {kind!=='event'&&<><MultiImageField label={kind==='gallery'?'Foto (1–3, wajib)':'Foto (maksimal 3)'} required={kind==='gallery'} values={imagesOf(f)} onChange={v=>{ch('images',v);ch('image',v[0]||'');}}/><Field label="Sumber / keterangan foto" value={f.imageCredit||''} onChange={e=>ch('imageCredit',e.target.value)}/></>}
 {(kind==='article'||kind==='product')&&<label className="check-field"><input type="checkbox" checked={f.featured} onChange={e=>ch('featured',e.target.checked)}/><span>Jadikan konten unggulan</span></label>}
 <div className="publish-box"><Field label={kind==='product'?'Keputusan / status publikasi':'Status publikasi'}><select value={f.status} onChange={e=>ch('status',e.target.value)}>{(!record?['draft','published']:kind==='product'?['draft','pending','published','revision','rejected','archived']:['draft','published','archived']).map(k=><option key={k} value={k}>{statusLabel[k]}</option>)}</select></Field>{kind==='product'&&text('moderationNote','Catatan untuk pengirim',['revision','rejected'].includes(f.status))}<p className="small muted">Hanya konten berstatus Terbit yang tampil pada website pengunjung.</p></div><Notice error>{error}</Notice><div className="form-actions"><button className="button" disabled={busy}><Save/>{busy?'Menyimpan…':'Simpan perubahan'}</button><button type="button" className="button secondary" onClick={close}>Batal</button></div></form></Modal>;
}
 const settingGroups=[
 ['beranda','Tampilan beranda',[]],
 ['identitas','Identitas & beranda',[['name','Nama singkat'],['identity','Identitas lengkap'],['area','Keterangan pada bilah atas'],['heroTitle','Judul beranda','textarea'],['heroText','Pengantar beranda','textarea'],['homeProfileTitle','Judul profil singkat di beranda'],['tourismIntro','Pengantar bagian wisata di beranda','textarea'],['marketIntro','Pengantar bagian potensi / lapak','textarea'],['projectsIntro','Pengantar bagian pembangunan','textarea'],['mapIntro','Pengantar bagian peta','textarea'],['weatherPlace','Nama lokasi pada widget cuaca'],['footer','Teks footer','textarea']]],
 ['profil','Profil, visi & misi',[['about','Profil singkat','textarea'],['history','Sejarah desa','textarea'],['vision','Visi desa','textarea'],['missions','Misi desa — satu misi per baris','textarea'],['geography','Wilayah & geografis','textarea']]],
 ['kontak','Kontak & jadwal',[['address','Alamat kantor','textarea'],['regionLines','Wilayah administratif (satu baris per tingkat) — tampil di peta Kontak','textarea'],['phone','Telepon'],['email','Email'],['mapUrl','Tautan Google Maps (HTTPS)'],['hours','Jam pelayanan'],['timezone','Zona waktu, misalnya Asia/Jakarta'],['officeLat','Latitude kantor desa (peta Kontak)'],['officeLng','Longitude kantor desa'],['villageLat','Latitude pusat desa (Peta Desa & cuaca)'],['villageLng','Longitude pusat desa']]],
 ['data','Data & statistik',[['dataPeriod','Periode data'],['dataSource','Sumber data'],['sourceUrl','Tautan sumber (HTTPS)']]],
 ['halaman','Pengantar halaman',[]],['tampilan','Menu, judul & kategori',[]],['kredit','Sumber & kredit foto',[]],['demo','Penanda demonstrasi',[['demoNote','Keterangan data demonstrasi','textarea']]]
];
function SiteEditor({site,onSaved,initialGroup='identitas'}){
 const[f,setF]=useState(structuredClone(site)),[group,setGroup]=useState(initialGroup),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false);
 useEffect(()=>setGroup(initialGroup),[initialGroup]);
 const ch=(k,v)=>{setF(o=>({...o,[k]:v}));setDirty(true);};
 useEffect(()=>{const handle=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handle);return()=>window.removeEventListener('beforeunload',handle);},[dirty]);
 const g=settingGroups.find(x=>x[0]===group);
 const rows=(key,title,unit)=><div className="editable-rows"><h3>{title}</h3>{f[key].map((r,i)=><div className="editable-row" key={i}><Field label="Label" value={r.label} onChange={e=>ch(key,f[key].map((x,n)=>n===i?{...x,label:e.target.value}:x))}/><Field label="Nilai" type={key==='stats'?'text':'number'} min="0" value={r.value} onChange={e=>ch(key,f[key].map((x,n)=>n===i?{...x,value:e.target.value}:x))}/>{unit&&<Field label="Satuan" value={r.unit} onChange={e=>ch(key,f[key].map((x,n)=>n===i?{...x,unit:e.target.value}:x))}/>}<button type="button" className="icon-button" aria-label={'Hapus '+r.label} onClick={()=>ch(key,f[key].filter((_,n)=>n!==i))}><Trash2/></button></div>)}<button type="button" className="button secondary" disabled={f[key].length>=12} onClick={()=>ch(key,[...f[key],{label:'Indikator baru',value:key==='stats'?'0':0,...(unit?{unit:'jiwa'}:{})}])}><Plus/>Tambah indikator</button></div>;
 return <div className="settings-layout"><div className="settings-tabs">{settingGroups.map(([k,l])=><button key={k} className={group===k?'active':''} onClick={()=>setGroup(k)}>{l}</button>)}</div><form className="panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/admin/site',{method:'PUT',body:f});setDirty(false);await onSaved(false);}catch(x){setError(x.message);}finally{setBusy(false);}}}><h3>{g[1]}</h3><div className="setting-fields">{g[2].map(([k,l,t])=><Field key={k} label={l}>{t==='textarea'?<textarea value={f[k]||''} onChange={e=>ch(k,e.target.value)}/>:<input value={f[k]||''} onChange={e=>ch(k,e.target.value)}/>}</Field>)}</div>{group==='beranda'&&<HomeSettings f={f} ch={ch}/>}
 {group==='halaman'&&Object.entries(f.pages).map(([key,copy])=><div className="credit-editor" key={key}><h4>{f.nav[key]}</h4>{[['eyebrow','Keterangan atas judul'],['title','Judul halaman'],['intro','Pengantar halaman']].map(([field,label])=><Field label={label} key={field} value={copy[field]} onChange={e=>ch('pages',{...f.pages,[key]:{...copy,[field]:e.target.value}})}/>)}</div>)}
 {group==='data'&&<>{rows('stats','Angka ringkas (beranda & profil)',true)}<DataSectionsEditor value={f.dataSections||[]} onChange={v=>ch('dataSections',v)}/></>}
 {group==='tampilan'&&<><h4>Nama menu</h4><div className="form-grid">{Object.entries(f.nav).map(([k,v])=><Field key={k} label={v} value={v} onChange={e=>ch('nav',{...f.nav,[k]:e.target.value})}/>)}</div><h4>Judul bagian</h4><div className="form-grid">{Object.entries(f.labels).map(([k,v])=><Field key={k} label={v} value={v} onChange={e=>ch('labels',{...f.labels,[k]:e.target.value})}/>)}</div><Field label="Kategori produk — satu per baris"><textarea value={f.productCategories.join('\n')} onChange={e=>ch('productCategories',e.target.value.split('\n'))}/></Field><Field label="Kategori agenda — satu per baris"><textarea value={f.eventCategories.join('\n')} onChange={e=>ch('eventCategories',e.target.value.split('\n'))}/></Field></>}
 {group==='kredit'&&<>{(f.credits||[]).map((r,i)=><div className="credit-editor" key={i}><div className="form-grid">{[['title','Nama foto'],['author','Fotografer'],['source','Tautan sumber'],['license','Lisensi'],['licenseUrl','Tautan lisensi']].map(([k,l])=><Field key={k} label={l} value={r[k]||''} onChange={e=>ch('credits',f.credits.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/>)}</div><button type="button" className="button danger" onClick={()=>ch('credits',f.credits.filter((_,n)=>n!==i))}>Hapus kredit</button></div>)}<button type="button" className="button secondary" onClick={()=>ch('credits',[...(f.credits||[]),{title:'',author:'',source:'',license:'',licenseUrl:''}])}>Tambah kredit foto</button></>}
 {group==='demo'&&<label className="check-field"><input type="checkbox" checked={f.demo} onChange={e=>ch('demo',e.target.checked)}/><span>Tampilkan penanda data demonstrasi. Nonaktifkan hanya setelah konten resmi diperiksa.</span></label>}
 <Notice error>{error}</Notice><div className="form-actions"><button className="button" disabled={busy}><Save/>{busy?'Menyimpan…':'Simpan perubahan'}</button>{dirty&&<span className="small muted">Ada perubahan yang belum disimpan</span>}</div></form></div>;
}
const pageTargets=[['/profil','Profil desa'],['/wisata','Wisata'],['/peta-desa','Peta Desa'],['/informasi','Informasi'],['/informasi?tab=agenda','Agenda'],['/galeri','Galeri'],['/lapak','Lapak desa'],['/pengaduan','Layanan warga'],['/pengaduan?buat=1','Buat pengaduan'],['/transparansi','Transparansi'],['/kontak','Kontak']];
// Homepage settings: village logo, hero slideshow (max 5), hero buttons, visible sections and their order, background motif.
function HomeSettings({f,ch}){
 const slides=f.heroSlides?.length?f.heroSlides:[{image:f.heroImage,caption:f.heroCaption||''}].filter(s=>s.image);
 const setImages=list=>ch('heroSlides',list.map(image=>({image,caption:slides.find(s=>s.image===image)?.caption||''})));
 const sections=[...(f.homeSections||[]).filter(s=>homeSectionKeys.includes(s.key)),...homeSectionKeys.filter(k=>!(f.homeSections||[]).some(s=>s.key===k)).map(key=>({key,visible:true}))];
 const move=(i,d)=>{const a=[...sections];[a[i],a[i+d]]=[a[i+d],a[i]];ch('homeSections',a);};
 const buttons=[0,1].map(i=>f.heroButtons?.[i]||{label:'',href:'/profil'});
 const setButton=(i,patch)=>ch('heroButtons',buttons.map((b,n)=>n===i?{...b,...patch}:b));
 return <div className="home-settings">
  <section><h4>Logo desa</h4><p className="small muted">Tampil di kepala halaman, footer, dan panel admin. Gunakan gambar persegi berlatar polos. Kosongkan untuk memakai monogram bawaan.</p><div className="logo-row"><BrandMark site={f}/><ImageField label="Unggah logo" value={f.logo} onChange={v=>ch('logo',v)}/>{f.logo&&<button type="button" className="plain-link danger-text" onClick={()=>ch('logo','')}>Hapus logo</button>}</div></section>
  <section><h4>Slide foto beranda</h4><MultiImageField label="Foto slide (maksimal 5)" max={5} values={slides.map(s=>s.image)} onChange={setImages} help="Foto berganti otomatis setiap 6 detik dan dapat digeser pengunjung. Gunakan foto asli atau foto berlisensi."/>{slides.map((s,i)=><Field key={s.image} label={'Keterangan foto '+(i+1)} value={s.caption} maxLength={200} onChange={e=>ch('heroSlides',slides.map((x,n)=>n===i?{...x,caption:e.target.value}:x))}/>)}</section>
  <section><h4>Tombol di foto utama</h4><div className="form-grid">{buttons.map((b,i)=><React.Fragment key={i}><Field label={'Teks tombol '+(i+1)+' (kosongkan untuk menyembunyikan)'} maxLength={40} value={b.label} onChange={e=>setButton(i,{label:e.target.value})}/><Field label={'Tujuan tombol '+(i+1)}><select value={b.href} onChange={e=>setButton(i,{href:e.target.value})}>{[...pageTargets,...(pageTargets.some(p=>p[0]===b.href)?[]:[[b.href,b.href]])].map(([h,l])=><option key={h} value={h}>{l}</option>)}</select></Field></React.Fragment>)}</div></section>
  <section><h4>Bagian yang tampil di beranda</h4><p className="small muted">Centang bagian yang ingin ditampilkan, lalu atur urutannya. Foto utama selalu tampil paling atas.</p><ol className="section-order">{sections.map((s,i)=><li key={s.key}><label className="check-field"><input type="checkbox" checked={s.visible!==false} onChange={e=>ch('homeSections',sections.map((x,n)=>n===i?{...x,visible:e.target.checked}:x))}/><span>{homeSectionLabels[s.key]}</span></label><div className="row-actions"><button type="button" className="icon-button" aria-label={'Naikkan '+homeSectionLabels[s.key]} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp/></button><button type="button" className="icon-button" aria-label={'Turunkan '+homeSectionLabels[s.key]} disabled={i===sections.length-1} onClick={()=>move(i,1)}><ArrowDown/></button></div></li>)}</ol></section>
  <section><h4>Motif latar website</h4><Field label="Motif" help="Budaya Banten: latar polos dengan ornamen batik Banten, ragam hias, dan tenun yang diolah transparan dari foto berlisensi (lihat Sumber & kredit foto)."><select value={f.backgroundStyle||'budaya'} onChange={e=>ch('backgroundStyle',e.target.value)}><option value="budaya">Budaya Banten (polos + ornamen)</option><option value="gelombang">Gelombang pesisir</option><option value="anyaman">Anyaman bambu</option><option value="polos">Polos</option></select></Field><div className={'bg-preview bg-'+(f.backgroundStyle||'budaya')} aria-hidden="true"/></section>
 </div>;
}
// Editor for village data groups (structure A–M of the EcoQuest reference document).
function DataSectionsEditor({value,onChange}){
 const set=(i,patch)=>onChange(value.map((s,n)=>n===i?{...s,...patch}:s));
 const setRow=(i,j,patch)=>set(i,{rows:value[i].rows.map((r,m)=>m===j?{...r,...patch}:r)});
 const move=(i,d)=>{const next=[...value];const j=i+d;if(j<0||j>=next.length)return;[next[i],next[j]]=[next[j],next[i]];onChange(next);};
 return <div className="editable-rows"><h3>Data desa per kelompok</h3><p className="small muted">Mengikuti struktur dokumen data desa EcoQuest (A. Geografi, B. Pemerintahan, C. Kependudukan, E. Pendidikan, F. Kesehatan, G. Pertanian, H. Ekonomi, I. Infrastruktur, J. Budaya, K. Wisata, L. Organisasi, M. UMKM). Pilih “Grafik batang” hanya untuk nilai angka.</p>
 {value.map((s,i)=><details className="section-editor" key={i}><summary><strong>{s.code}. {s.title}</strong><span className="small muted"> · {s.rows.length} baris · {s.chart==='bar'?'grafik':'tabel'}</span></summary>
  <div className="form-grid"><Field label="Kode kelompok" maxLength={4} value={s.code} onChange={e=>set(i,{code:e.target.value})}/><Field label="Judul" value={s.title} onChange={e=>set(i,{title:e.target.value})}/><Field label="Tampilan"><select value={s.chart} onChange={e=>set(i,{chart:e.target.value})}><option value="table">Tabel</option><option value="bar">Grafik batang (angka)</option></select></Field><Field label="Tautan halaman (opsional)" placeholder="/wisata" value={s.link||''} onChange={e=>set(i,{link:e.target.value})}/></div>
  <Field label="Catatan singkat (opsional)" value={s.note||''} onChange={e=>set(i,{note:e.target.value})}/>
  {s.rows.map((r,j)=><div className="editable-row" key={j}><Field label="Uraian" value={r.label} onChange={e=>setRow(i,j,{label:e.target.value})}/><Field label="Nilai" value={r.value} onChange={e=>setRow(i,j,{value:e.target.value})}/><Field label="Satuan" value={r.unit} onChange={e=>setRow(i,j,{unit:e.target.value})}/><button type="button" className="icon-button" aria-label={'Hapus baris '+r.label} onClick={()=>set(i,{rows:s.rows.filter((_,m)=>m!==j)})}><Trash2/></button></div>)}
  <div className="form-actions"><button type="button" className="button secondary" disabled={s.rows.length>=40} onClick={()=>set(i,{rows:[...s.rows,{label:'Uraian baru',value:'0',unit:''}]})}><Plus/>Tambah baris</button><button type="button" className="button secondary" disabled={i===0} onClick={()=>move(i,-1)}>Naikkan</button><button type="button" className="button secondary" disabled={i===value.length-1} onClick={()=>move(i,1)}>Turunkan</button><button type="button" className="button danger" onClick={()=>{if(confirm('Hapus kelompok “'+s.title+'”?'))onChange(value.filter((_,n)=>n!==i));}}><Trash2/>Hapus kelompok</button></div>
 </details>)}
 <button type="button" className="button secondary" disabled={value.length>=24} onClick={()=>onChange([...value,{code:'',title:'Kelompok data baru',chart:'table',note:'',link:'',rows:[{label:'Uraian',value:'0',unit:''}]}])}><Plus/>Tambah kelompok data</button></div>;
}
function Account(){const[f,setF]=useState({currentPassword:'',password:'',confirm:''}),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <form className="panel account-panel" onSubmit={async e=>{e.preventDefault();setError('');setMessage('');if(f.password!==f.confirm)return setError('Konfirmasi kata sandi tidak sama.');setBusy(true);try{await api('/admin/password',{method:'PUT',body:f});setMessage('Kata sandi berhasil diganti. Sesi lain telah dikeluarkan.');setF({currentPassword:'',password:'',confirm:''});}catch(x){setError(x.message);}finally{setBusy(false);}}}><h3>Ganti kata sandi</h3><p className="muted small">Gunakan minimal 12 karakter dan simpan di tempat yang aman.</p>{[['currentPassword','Kata sandi lama'],['password','Kata sandi baru'],['confirm','Ulangi kata sandi baru']].map(([k,l])=><Field key={k} label={l} type="password" autoComplete={k==='currentPassword'?'current-password':'new-password'} minLength={k==='currentPassword'?1:12} value={f[k]} required onChange={e=>setF({...f,[k]:e.target.value})}/>)}<Notice error>{error}</Notice><Notice>{message}</Notice><button className="button" disabled={busy}>{busy?'Menyimpan…':'Ganti kata sandi'}</button></form>;}
export default function Admin({refreshPublic}){
 const[authenticated,setAuthenticated]=useState(null),[records,setRecords]=useState(null),[module,setModule]=useState('dashboard'),[editor,setEditor]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[q,setQ]=useState(''),[filter,setFilter]=useState('all'),[menu,setMenu]=useState(false),[counts,setCounts]=useState({complaints:0,unread:0}),[dashKey,setDashKey]=useState(0);
 const groups=menu_groups;
 const loadCounts=async()=>{try{const s=await api('/admin/summary');setCounts({complaints:s.complaints.baru,unread:s.unread});}catch{}};
 useEffect(()=>{if(!authenticated)return;loadCounts();const t=setInterval(()=>{if(document.visibilityState==='visible')loadCounts();},30000);return()=>clearInterval(t);},[authenticated]);
 const load=async()=>{try{const r=await api('/admin/content');setRecords(r);}catch(e){setError(e.message);}};
 useEffect(()=>{api('/session').then(r=>setAuthenticated(r.authenticated)).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(authenticated)load();},[authenticated]);
 const saved=async(close=true)=>{await load();await refreshPublic();if(close)setEditor(null);setMessage('Perubahan berhasil disimpan.');};
 const choose=k=>{setModule(k);setQ('');setFilter('all');setMessage('');setError('');setMenu(false);if(k==='dashboard'){setDashKey(n=>n+1);loadCounts();}window.scrollTo(0,0);};
 if(authenticated===null)return error?<Notice error>{error}</Notice>:<Busy/>;
 if(!authenticated)return <Login onLogin={()=>setAuthenticated(true)}/>;
 if(!records)return error?<Notice error>{error}</Notice>:<Busy/>;
 const site=records.find(r=>r.kind==='site'),products=records.filter(r=>r.kind==='product'),pending=products.filter(r=>r.status==='pending').length;
 const list=records.filter(r=>r.kind===module&&(filter==='all'||r.status===filter)&&(r.title+' '+(r.seller||'')).toLowerCase().includes(q.toLowerCase()));
 const current=modules.find(m=>m[0]===module)||modules[0],siteGroup=module.startsWith('site')?module.split(':')[1]||'identitas':null;
 const badge=k=>k==='product'?pending:k==='complaints'?counts.complaints:k==='inbox'?counts.unread:0;
 return <div className="admin-shell"><aside className={'admin-sidebar '+(menu?'open':'')}><Link href="/" className="brand"><BrandMark site={site}/><span><small>ADMIN DESA</small><strong>{site.name}</strong></span></Link><nav aria-label="Menu admin">{groups.map(([label,items])=><div className="admin-menu-group" key={label||'main'}>{label&&<div className="admin-menu-label">{label}</div>}{items.map(([k,l,Icon])=><button key={k} className={module===k?'active':''} aria-current={module===k?'page':undefined} onClick={()=>choose(k)}><Icon size={19}/><span>{l}</span>{badge(k)>0&&<b aria-label={badge(k)+' perlu perhatian'}>{badge(k)}</b>}</button>)}</div>)}</nav><div className="admin-sidebar-bottom"><Link href="/"><ExternalLink size={17}/>Lihat website</Link><button onClick={async()=>{await api('/logout',{method:'POST'});setAuthenticated(false);setRecords(null);}}><LogOut size={17}/>Keluar</button></div></aside>{menu&&<div className="admin-scrim" onClick={()=>setMenu(false)} aria-hidden="true"/>}<div className="admin-workspace"><header className="admin-top"><button className="icon-button mobile-toggle" onClick={()=>setMenu(!menu)} aria-label="Menu admin" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button><span>Pengelolaan website · {site.identity}</span><span><ShieldCheck size={16}/>Admin</span></header><main className="admin-main"><div className="admin-heading"><div><span className="eyebrow">PANEL ADMIN</span><h1>{current[1]}</h1></div>{kindNames[module]&&<button className="button" onClick={()=>setEditor({record:null,kind:module})}><Plus/>Tambah {kindNames[module]}</button>}</div>{moduleHelp[module]&&<p className="form-intro admin-help">{moduleHelp[module]}</p>}<Notice>{message}</Notice><Notice error>{error}</Notice>
 {module==='dashboard'?<PortalDashboard key={dashKey} records={records} go={choose}/>:siteGroup?<SiteEditor site={site} initialGroup={siteGroup} onSaved={saved}/>:module==='registration'?<RegistrationAdmin records={records} refreshPublic={refreshPublic}/>:module==='account'?<Account/>:module==='complaints'?<ComplaintsAdmin onChanged={loadCounts} site={site}/>:module==='inbox'?<Inbox onChanged={loadCounts}/>:portalTables.includes(module)?<TableManager key={module} table={module} onChanged={refreshPublic}/>:<><div className="filter-bar"><div className="search-field"><Search/><input aria-label="Cari konten admin" placeholder="Cari judul atau nama penjual…" value={q} onChange={e=>setQ(e.target.value)}/></div><select aria-label="Status konten" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua status</option>{(module==='product'?Object.keys(statusLabel):['published','draft','archived']).map(k=><option key={k} value={k}>{statusLabel[k]}</option>)}</select><span className="result-count">{list.length} konten</span></div><div className="records-list">{list.length?list.map(r=><div className="record-row" key={r.id}>{r.image?<Picture src={r.image} alt="" className="record-thumbnail"/>:<div className="record-thumbnail calendar-thumb"><CalendarDays/></div>}<div className="record-title"><strong>{r.title}</strong><p>{r.category}{r.seller?' · '+r.seller:''}{r.date?' · '+dateLabel(r.date):''}{r.kind==='gallery'?' · urutan '+(r.sortOrder??100):''}</p></div><span className={'status '+r.status}>{statusLabel[r.status]}</span><div className="row-actions">{r.kind==='gallery'&&<button className="icon-button" aria-label={(r.status==='published'?'Sembunyikan ':'Terbitkan ')+r.title} title={r.status==='published'?'Unpublish':'Publish'} onClick={async()=>{try{await api('/admin/records/'+r.id,{method:'PUT',body:{...r,status:r.status==='published'?'draft':'published'}});await saved(false);}catch(e){setError(e.message);}}}>{r.status==='published'?<EyeOff/>:<Eye/>}</button>}<button className="icon-button" aria-label={'Edit '+r.title} onClick={()=>setEditor({record:r,kind:r.kind})}><Pencil/></button><button className="icon-button danger-text" aria-label={'Hapus '+r.title} onClick={async()=>{if(!confirm('Hapus “'+r.title+'”? Tindakan ini tidak dapat dibatalkan.'))return;try{await api('/admin/records/'+r.id,{method:'DELETE'});await saved(false);}catch(e){setError(e.message);}}}><Trash2/></button></div></div>):<Empty title="Konten belum ditemukan" text="Ubah pencarian atau tambahkan konten baru."/>}</div></>}
 </main></div>{editor&&<RecordEditor {...editor} site={site} products={products} onClose={()=>setEditor(null)} onSaved={saved}/>}</div>;
}
