import React,{useEffect,useState} from 'react';
import {Search,Users,Store,RefreshCw,ShieldCheck} from 'lucide-react';
import {api,Field,Modal,Notice,Empty,Busy,dateLabel} from './lib.jsx';
import {registrationLabels,registrationModes} from './event-registration.jsx';

function Review({record,event,products,onClose,onSaved}){
  const [status,setStatus]=useState(record.status),[note,setNote]=useState(record.note),[productId,setProductId]=useState(record.productId),[attended,setAttended]=useState(record.attended),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <Modal title="Tinjau pendaftaran" wide onClose={onClose}><span className="tag">{registrationModes[record.mode]}</span><h3 className="registration-event-title">{event?.title||'Agenda tidak tersedia'}</h3><div className="privacy-note"><ShieldCheck size={19}/><p>Identitas pemohon hanya terlihat oleh admin. Persetujuan tidak memublikasikan alamat, kontak, atau RT/RW.</p></div><dl className="applicant-details">{[['Nama lengkap',record.name],['Alamat tempat tinggal',record.address],['Nomor HP / WhatsApp',record.phone],['RT / RW',record.rt+' / '+record.rw],...(record.mode==='stall'?[['Nama usaha',record.businessName],['Produk yang akan dijual',record.productSummary]]:[])].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><form onSubmit={async e=>{
    e.preventDefault();setBusy(true);setError('');try{await api('/admin/event-registrations/'+record.id,{method:'PUT',body:{status,note,productId,attended,updatedAt:record.updatedAt}});await onSaved();}catch(err){setError(err.message);}finally{setBusy(false);}
  }}><Field label="Keputusan pendaftaran"><select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(registrationLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="Catatan untuk pemohon" help="Catatan dapat dibaca pemohon melalui kode pribadinya."><textarea required={['revision','rejected','cancelled'].includes(status)} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></Field>{record.mode==='stall'&&<Field label="Hubungkan produk Lapak Desa (opsional)" help="Pastikan produk ini milik usaha pemohon. Produk yang sudah terbit akan muncul pada halaman acara setelah pendaftaran disetujui."><select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Tanpa produk terkait</option>{products.filter(p=>p.status==='published').map(p=><option key={p.id} value={p.id}>{p.title} — {p.seller}</option>)}{productId&&!products.some(p=>p.id===productId&&p.status==='published')&&<option value={productId}>Produk tidak lagi terbit — pilih ulang</option>}</select></Field>}{status==='approved'&&<label className="check-field"><input type="checkbox" checked={attended} onChange={e=>setAttended(e.target.checked)}/><span>Pemohon sudah hadir dalam kegiatan</span></label>}<Notice error>{error}</Notice><div className="form-actions"><button className="button" disabled={busy}>{busy?'Menyimpan…':'Simpan keputusan'}</button><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Tutup</button></div></form></Modal>;
}
export default function RegistrationAdmin({records,refreshPublic}){
  const [items,setItems]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[eventId,setEventId]=useState('all'),[status,setStatus]=useState('all'),[mode,setMode]=useState('all'),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[refreshing,setRefreshing]=useState(false);
  const load=async()=>{setRefreshing(true);try{setItems(await api('/admin/event-registrations'));setError('');}catch(err){setError(err.message);}finally{setRefreshing(false);}};
  useEffect(()=>{load();},[]);
  const events=records.filter(r=>r.kind==='event'),products=records.filter(r=>r.kind==='product');
  const eventName=id=>events.find(e=>e.id===id)?.title||'Agenda tidak tersedia';
  const filtered=(items||[]).filter(r=>(eventId==='all'||r.eventId===eventId)&&(status==='all'||r.status===status)&&(mode==='all'||r.mode===mode)&&[r.name,r.businessName,r.phone,r.rt,r.rw,eventName(r.eventId)].join(' ').toLowerCase().includes(search.toLowerCase()));
  const eventItems=(items||[]).filter(r=>eventId==='all'||r.eventId===eventId);
  const stats=[['Menunggu',eventItems.filter(r=>r.status==='pending').length],['Perlu perbaikan',eventItems.filter(r=>r.status==='revision').length],['Disetujui',eventItems.filter(r=>r.status==='approved').length],['Sudah hadir',eventItems.filter(r=>r.attended).length]];
  return <><p className="form-intro">Periksa identitas pemohon, kelola kuota melalui Agenda desa, dan catat keputusan di sini. Data pemohon tidak ditampilkan kepada pengunjung.</p><div className="registration-summary">{stats.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><Notice error>{error}</Notice><Notice>{message}</Notice><div className="registration-filters"><Field label="Kegiatan"><select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="all">Semua kegiatan</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></Field><Field label="Jenis pendaftaran"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="all">Peserta & lapak bazar</option>{Object.entries(registrationModes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="Status pendaftaran"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Semua status</option>{Object.entries(registrationLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field></div><div className="filter-bar"><div className="search-field"><Search/><input aria-label="Cari pemohon" placeholder="Cari nama, usaha, nomor, atau RT/RW…" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="button secondary" disabled={refreshing} onClick={load}><RefreshCw size={16}/>{refreshing?'Memuat…':'Muat ulang'}</button><span className="result-count">{filtered.length} pendaftaran</span></div>{items===null?!error&&<Busy/>:<div className="records-list">{filtered.length?filtered.map(r=><div className="registration-row" key={r.id}><div className="registration-symbol">{r.mode==='stall'?<Store/>:<Users/>}</div><div className="registration-person"><strong>{r.name}</strong><p>{registrationModes[r.mode]} · RT {r.rt} / RW {r.rw}</p><p>{eventName(r.eventId)}{r.businessName?' · '+r.businessName:''}</p></div><span className={'status '+r.status}>{registrationLabels[r.status]}</span><button className="button secondary" onClick={()=>{setSelected(r);setMessage('');}}>Tinjau</button>{['rejected','cancelled'].includes(r.status)&&<button className="plain-link danger-text" onClick={async()=>{if(!confirm('Hapus permanen data pendaftaran '+r.name+'? Kode pemohon tidak akan dapat dipakai lagi.'))return;try{await api('/admin/event-registrations/'+r.id,{method:'DELETE'});await load();setMessage('Data pendaftaran telah dihapus.');}catch(err){setError(err.message);}}}>Hapus</button>}</div>):<Empty title="Belum ada pendaftaran yang sesuai" text="Pengajuan peserta dan lapak bazar akan muncul di sini."/>}</div>}{selected&&<Review record={selected} event={events.find(e=>e.id===selected.eventId)} products={products} onClose={()=>setSelected(null)} onSaved={async()=>{await load();await refreshPublic();setSelected(null);setMessage('Keputusan tersimpan. Pemohon dapat mengeceknya melalui kode pendaftaran.');}}/>}</>;
}
